name: Build native application and Chrome Extension

on: workflow_dispatch

jobs:

  build-native:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build native application
      run: go build
      working-directory: ./native-application


  build-extension:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 17.4

    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Build chrome extension
      working-directory: chrome-extension
      run: |
        yarn
        yarn build

    # https://github.com/marketplace/actions/action-zip
    - name: Zip chrome extension
      working-directory: chrome-extension
      run: zip -qq -r extension.zip dist

    # - name: Create release on GitHub
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     draft: true
    #     files: |
    #       native-application/probable-invention.exe
    #       chrome-extension/extension.zip


  create-draft-release:
    runs-on: ubuntu-latest
    steps:
    - name: Create release on GitHub
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          native-application/probable-invention.exe
          chrome-extension/extension.zip
